

### Teste simples
GET http://localhost:8084/api/clientes/testeCliente1

### Teste com PathVariable
GET http://localhost:8084/api/clientes/testeCliente2/Danilo

### Criar Cliente
POST http://localhost:8084/api/clientes
Content-Type: application/json

{
  "id": 5
  "nome": "Zé da Silva"
  "endereco": "zzzz"
}

### Listar Clientes

GET http://localhost:8084/api/clientes/listarClientes


### Remover cliente

DELETE http://localhost:8084/api/clientes/2



### Alterar cliente

PUT http://localhost:8084/api/clientes

{

"id": 1;
"nome": abraão;

}